name: Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build Docker image
      run: docker build -t weather-frontend:dev .

    - name: Log in to Azure Container Registry
      uses: azure/docker-login@v1
      with:
        login-server: devops9nestcandidate.azurecr.io
        username: devops9nestcandidate
        password: 3y06K395LOQQ1TywBf1JV0VUicrgIbdbCq/8ZPw83y+ACRDG3yfh

    - name: Tag Image
      run: docker tag weather-frontend:dev devops9nestcandidate.azurecr.io/weather-frontend:dev

    - name: Push Docker image
      run: docker push devops9nestcandidate.azurecr.io/weather-frontend:dev
