name: Build, Push, and Deploy

on:
  push:
    branches: [ "main" ]

env:
  ACR_NAME: devops9nestcandidate      
  IMAGE_NAME: weather-frontend
  TAG: latest
  RESOURCE_GROUP: rg-devops-candidate
  AKS_CLUSTER: DevOps-Candidate

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build Docker image
      run: docker build -t ${{ env.IMAGE_NAME }}:${{ env.TAG }} .

    - name: Login to Azure Container Registry
      uses: azure/docker-login@v1
      with:
        login-server: ${{ env.ACR_NAME }}.azurecr.io
        username: ${{ secrets.ACR_USERNAME }}
        password: ${{ secrets.ACR_PASSWORD }}

    - name: Push Docker image
      run: |
        docker tag ${{ env.IMAGE_NAME }}:${{ env.TAG }} ${{ env.ACR_NAME }}.azurecr.io/${{ env.IMAGE_NAME }}:${{ env.TAG }}
        docker push ${{ env.ACR_NAME }}.azurecr.io/${{ env.IMAGE_NAME }}:${{ env.TAG }}

    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CRED }}

    - name: Get AKS credentials
      uses: azure/aks-set-context@v3
      with:
        resource-group: ${{ env.RESOURCE_GROUP }}
        cluster-name: ${{ env.AKS_CLUSTER }}

    - name: Deploy to AKS
      run: |
        kubectl apply -f k8s/
